LOCAL_PATH := $(call my-dir)

KERNEL_OUT := $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr
TARGET_PREBUILT_KERNEL_INCLUDE := $(KERNEL_OUT)

$(TARGET_PREBUILT_KERNEL_INCLUDE):
	mkdir -p $(KERNEL_OUT)
	cp -rf $(LOCAL_PATH)/kernel/include $(KERNEL_OUT)/

$(INSTALLED_KERNEL_TARGET): $(TARGET_PREBUILT_KERNEL) | $(ACP) $(TARGET_PREBUILT_KERNEL_INCLUDE)
	$(transform-prebuilt-to-target)
